### ISSUE TITLE
How to use restful way node api call

### ISSUE THREAD

**Issue by COLUD4** [RunOnFlux/fluxd#207]
I created a local node, but how can I use the restful api call method. Something like this:curl curl http://188.165.223.164:16127/daemon/getblockhash/1

**Comment by blondfrogs** [comment]
@COLUD4 Sorry for the delay. In order to do something like this you need to have a restful api running along side the local node daemon. 

You can also create direct http calls to the daemon using curl. 

that command would look something like 

`curl --user StandUp --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getmininginfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:18332/`

You can find more information about that here [Blockchain Communications](https://github.com/BlockchainCommons/Learning-Bitcoin-from-the-Command-Line/blob/master/04_4__Interlude_Using_Curl.md)

**Comment by blondfrogs** [comment]
@COLUD4 Closing as this has been answered.
